services:
  db:
    image: postgres:17
    container_name: radarius_db
    environment:
      POSTGRES_USER: denarius
      POSTGRES_PASSWORD: denarius
      POSTGRES_DB: radarius
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: