spring:
  application:
    name: radarius
  datasource:
    url: jdbc:oracle:thin:@${TNS_NAME}?TNS_ADMIN=${WALLET_DIR}
    username: DEN_AUGUSTO
    password: Radarius2025
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSourceImpl
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      connection-pool-name: ADBExample
      initial-pool-size: 5
      min-pool-size: 1
      max-pool-size: 30
      shared: true
  jpa:
    hibernate:
      ddl-auto: validate

cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,PATCH,DELETE

security:
  jwt:
    secret-key: radarius
